### ISSUE TITLE
Rename data science sandbox to exasol-ai-lab

### ISSUE THREAD

**Issue by ckunki** [exasol/ai-lab#79]
Ticket #5 already described initial renaming after DSS was derived from script-languages-developer-sandbox.

After naming committee has defined a company branding the current ticket request an additional renaming action. 

Renaming should include 
* Docker-hub
* Git-Repo
* Code references

**Comment by tkilias** [comment]
More places to rename

doc/user_guide/user_guide.md:31:At the first login to the sandbox (image or AMI) you will be prompted to change your password.

doc/user_guide/ami_usage.md:27:     - At field "Application and OS Images" select the AMI id of the sandbox (found in the [release notes](https://github.com/exasol/ai-lab/releases/latest))

doc/developer_guide/aws.md:53:The EC2-stack lives only during the creation of a new sandbox image.
doc/developer_guide/aws.md:67:* If the creation of a sandbox finished normally the list should contain only the AMI, images (S3 objects) and the export tasks (one for each image).

exasol/ds/sandbox/lib/dss_docker/create_image.py:85:        self.container_name = f"ds-sandbox-{DssDockerImage.timestamp()}"

exasol/ds/sandbox/lib/asset_id.py:2:    def __init__(self, asset_id: str, stack_prefix="EC2-DATA-SCIENCE-SANDBOX-", ami_prefix="Exasol-AI-Lab"): # the stack prefix can be renamed, because it only is the EC2 Stack

exasol/ds/sandbox/runtime/ansible/roles/jupyter/files/notebook/setup_db.ipynb:24:    "conf = SandboxConfig(EXTERNAL_HOST_NAME=\"127.0.0.1\", HOST_PORT=8563)\n",
